name: Scheduled docker image build
on:
  push:
  schedule:
    - cron: '0 12 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Yarn install
        run: yarn
      - name: Yarn start
        run: yarn start
