name: Scheduled docker image build
on:
  push:
  schedule:
    - cron: '0 12 * * 1'

jobs:
  build:
    name: 'Build and push containers'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Yarn install
        run: yarn
      - name: Yarn start
        run: yarn start
